### ISSUE TITLE
pio train exception

### ISSUE THREAD

**Issue by gaoxuesong** [apache/incubator-predictionio#275]
After successful pio build, I run pio train command. In the end of the train, it occur exception. How to fix it?
The running log as following.

root@dev2:~/PredictionIO-0.9.6/MyRecommendation# pio train
[INFO] [Console$] Using existing engine manifest JSON at /root/PredictionIO-0.9.6/MyRecommendation/manifest.json
[INFO] [Runner$] Submission command: /root/PredictionIO-0.9.6/vendors/spark-1.5.1-bin-hadoop2.6/bin/spark-submit --class io.prediction.workflow.CreateWorkflow --jars file:/root/PredictionIO-0.9.6/MyRecommendation/target/scala-2.10/template-scala-parallel-recommendation_2.10-0.1-SNAPSHOT.jar,file:/root/PredictionIO-0.9.6/MyRecommendation/target/scala-2.10/template-scala-parallel-recommendation-assembly-0.1-SNAPSHOT-deps.jar --files file:/root/PredictionIO-0.9.6/conf/log4j.properties --driver-class-path /root/PredictionIO-0.9.6/conf:/root/PredictionIO-0.9.6/lib/mysql-connector-java-5.1.37.jar file:/root/PredictionIO-0.9.6/lib/pio-assembly-0.9.6.jar --engine-id LmGxRk1pTvLml0pFpCmaK9VXv7f4QkI5 --engine-version 62a3e38da04525b30004dc6c6d42ea588828031c --engine-variant file:/root/PredictionIO-0.9.6/MyRecommendation/engine.json --verbosity 0 --json-extractor Both --env PIO_ENV_LOADED=1,PIO_STORAGE_SOURCES_MYSQL_PASSWORD=passw0rd,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta,PIO_FS_BASEDIR=/root/.pio_store,PIO_STORAGE_SOURCES_MYSQL_URL=jdbc:mysql://10.18.218.9:13306/pio,PIO_HOME=/root/PredictionIO-0.9.6,PIO_FS_ENGINESDIR=/root/.pio_store/engines,PIO_STORAGE_SOURCES_MYSQL_TYPE=jdbc,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=MYSQL,PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=MYSQL,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event,PIO_STORAGE_SOURCES_MYSQL_USERNAME=root,PIO_FS_TMPDIR=/root/.pio_store/tmp,PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=MYSQL,PIO_CONF_DIR=/root/PredictionIO-0.9.6/conf
[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(MyApp1,None))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[WARN] [Utils] Your hostname, dev2 resolves to a loopback address: 127.0.1.1; using 10.18.218.100 instead (on interface eth0)
[WARN] [Utils] Set SPARK_LOCAL_IP if you need to bind to another address
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@10.18.218.100:44414]
[WARN] [MetricsSystem] Using default name DAGScheduler for source because spark.app.id is not set.
[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: org.template.recommendation.DataSource@3fc7c734
[INFO] [Engine$] Preparator: org.template.recommendation.Preparator@1cf336fd
[INFO] [Engine$] AlgorithmList: List(org.template.recommendation.ALSAlgorithm@5dfe23e8)
[INFO] [Engine$] Data sanity check is on.
[INFO] [Engine$] org.template.recommendation.TrainingData does not support data sanity check. Skipping check.
[INFO] [Engine$] org.template.recommendation.PreparedData does not support data sanity check. Skipping check.
[WARN] [BLAS] Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
[WARN] [BLAS] Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
[WARN] [LAPACK] Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
[WARN] [LAPACK] Failed to load implementation from: com.github.fommil.netlib.NativeRefLAPACK
[INFO] [Engine$] org.apache.spark.mllib.recommendation.ALSModel does not support data sanity check. Skipping check.
[INFO] [Engine$] EngineWorkflow.train completed
[INFO] [Engine] engineInstanceId=71d2ba4e-fed0-49f3-9bb2-90fead6818e6
[INFO] [CoreWorkflow$] Inserting persistent model
[INFO] [CoreWorkflow$] Updating engine instance
[INFO] [CoreWorkflow$] Training completed successfully.

Exception in thread "Thread-3" java.net.ConnectException: 拒绝连接
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at java.net.URL.openStream(URL.java:1045)
        at scala.io.Source$.fromURL(Source.scala:140)
        at scala.io.Source$.fromURL(Source.scala:130)
        at io.prediction.workflow.UpgradeCheckRunner.run(WorkflowUtils.scala:400)

**Comment by Christophy** [comment]
Hi, XueSong, you may already figured out, despite the connection error, your engine is trained and inserted successfully. 
So maybe there is a request made after the training process is completed. I am also curious about this. 
so which template are you using?

**Comment by gaoxuesong** [comment]
recommendation template

**Comment by dszeto** [comment]
Hi, please redirect usage questions to user@predictionio.incubator.apache.org for more exposure to the rest of the community. Subscription instructions can be found at http://predictionio.incubator.apache.org/support/.

@Christophy is right. Despite the stack trace that you are seeing, all `pio` commands will still complete successfully. The upcoming release will have this fixed. Thanks for the patience.
