### ISSUE TITLE
pio deploy exception

### ISSUE THREAD

**Issue by gaoxuesong** [apache/incubator-predictionio#276]
When I run pio deploy command, I try to retrieve predicted results. It occur exception and I want to know how to fix it?
Then console message similar to the following:

root@dev2:~/PredictionIO-0.9.6/MyRecommendation# pio deploy
[INFO] [Runner$] Submission command: /root/PredictionIO-0.9.6/vendors/spark-1.5.1-bin-hadoop2.6/bin/spark-submit --class io.prediction.workflow.CreateServer --jars file:/root/PredictionIO-0.9.6/MyRecommendation/target/scala-2.10/template-scala-parallel-recommendation_2.10-0.1-SNAPSHOT.jar,file:/root/PredictionIO-0.9.6/MyRecommendation/target/scala-2.10/template-scala-parallel-recommendation-assembly-0.1-SNAPSHOT-deps.jar --files file:/root/PredictionIO-0.9.6/conf/log4j.properties --driver-class-path /root/PredictionIO-0.9.6/conf:/root/PredictionIO-0.9.6/lib/mysql-connector-java-5.1.37.jar file:/root/PredictionIO-0.9.6/lib/pio-assembly-0.9.6.jar --engineInstanceId 68496049-6adc-4dd0-b4f5-395854919c96 --engine-variant file:/root/PredictionIO-0.9.6/MyRecommendation/engine.json --ip 0.0.0.0 --port 8000 --event-server-ip 0.0.0.0 --event-server-port 7070 --json-extractor Both --env PIO_ENV_LOADED=1,PIO_STORAGE_SOURCES_MYSQL_PASSWORD=passw0rd,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta,PIO_FS_BASEDIR=/root/.pio_store,PIO_STORAGE_SOURCES_MYSQL_URL=jdbc:mysql://10.18.218.9:13306/pio,PIO_HOME=/root/PredictionIO-0.9.6,PIO_FS_ENGINESDIR=/root/.pio_store/engines,PIO_STORAGE_SOURCES_MYSQL_TYPE=jdbc,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=MYSQL,PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=MYSQL,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event,PIO_STORAGE_SOURCES_MYSQL_USERNAME=root,PIO_FS_TMPDIR=/root/.pio_store/tmp,PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=MYSQL,PIO_CONF_DIR=/root/PredictionIO-0.9.6/conf
[WARN] [WorkflowUtils$] Non-empty parameters supplied to org.template.recommendation.Preparator, but its constructor does not accept any arguments. Stubbing with empty parameters.
[WARN] [WorkflowUtils$] Non-empty parameters supplied to org.template.recommendation.Serving, but its constructor does not accept any arguments. Stubbing with empty parameters.
[WARN] [Utils] Your hostname, dev2 resolves to a loopback address: 127.0.1.1; using 10.18.218.100 instead (on interface eth0)
[WARN] [Utils] Set SPARK_LOCAL_IP if you need to bind to another address
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@10.18.218.100:33114]
[WARN] [MetricsSystem] Using default name DAGScheduler for source because spark.app.id is not set.
[INFO] [Engine] Using persisted model
[INFO] [Engine] Custom-persisted model detected for algorithm org.template.recommendation.ALSAlgorithm
[WARN] [ALSModel] User factor does not have a partitioner. Prediction on individual records could be slow.
[WARN] [ALSModel] User factor is not cached. Prediction could be slow.
[WARN] [ALSModel] Product factor does not have a partitioner. Prediction on individual records could be slow.
[WARN] [ALSModel] Product factor is not cached. Prediction could be slow.
[INFO] [MasterActor] Undeploying any existing engine instance at https://0.0.0.0:8000
[WARN] [MasterActor] Nothing at https://0.0.0.0:8000
[INFO] [HttpListener] Bound to /0.0.0.0:8000
[INFO] [MasterActor] Engine is deployed and running. Engine API is live at https://0.0.0.0:8000.
[ERROR] [OneForOneStrategy] Cannot support TLS_RSA_WITH_AES_256_CBC_SHA with currently installed providers
Exception in thread "Thread-1" java.net.ConnectException: 拒绝连接
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at java.net.URL.openStream(URL.java:1045)
        at scala.io.Source$.fromURL(Source.scala:140)
        at scala.io.Source$.fromURL(Source.scala:130)
        at io.prediction.workflow.UpgradeCheckRunner.run(WorkflowUtils.scala:400)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Christophy** [comment]
Hello, XueSong, As you noticed from the post above , your engine was deployed in the 'https' protocal. In my practice, install the JCE can solve this "TLS_RSA_WITH_AES_256_CBC_SHA" problem.
link:

http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html


Hopefully in the next release pio can let user select whether to use "https" or not.

**Comment by gaoxuesong** [comment]
Hi Christophy,
Thanks for ur help.
