### ISSUE TITLE
FATAL:  role "pio" does not exist

### ISSUE THREAD

**Issue by iamShantanu101** [apache/incubator-predictionio#317]
Getting the below message when I tried pio app new tapster. This is related to postgres I guess. 
FATAL : role "pio" does not exist

Exception in thread "main" org.postgresql.util.PSQLException: FATAL: role "pio" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:691)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:65)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:156)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:35)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:47)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:30)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.apache.commons.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:77)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	at scalikejdbc.Commons2ConnectionPool.borrow(Commons2ConnectionPool.scala:41)
	at scalikejdbc.DB$.autoCommit(DB.scala:214)
	at io.prediction.data.storage.jdbc.JDBCApps.<init>(JDBCApps.scala:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.prediction.data.storage.Storage$.getDataObject(Storage.scala:303)
	at io.prediction.data.storage.Storage$.getDataObjectFromRepo(Storage.scala:263)
	at io.prediction.data.storage.Storage$.getMetaDataApps(Storage.scala:370)
	at io.prediction.tools.console.App$.create(App.scala:33)
	at io.prediction.tools.console.Console$$anonfun$main$1.apply(Console.scala:739)
	at io.prediction.tools.console.Console$$anonfun$main$1.apply(Console.scala:693)
	at scala.Option.map(Option.scala:145)
	at io.prediction.tools.console.Console$.main(Console.scala:693)
	at io.prediction.tools.console.Console.main(Console.scala)

**Comment by Talamantez** [comment]
source bin/env.sh && ./sbt run
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0

[info] Loading project definition from /Users/roberttalamantez/Documents/Champagne/machine-learning/prediction-io-app/pio-eventserver-heroku/project
[info] Set current project to pio-eventserver-heroku (in build file:/Users/roberttalamantez/Documents/Champagne/machine-learning/prediction-io-app/pio-eventserver-heroku/)
[info] Running EventServerApp 
[INFO] [Slf4jLogger] Slf4jLogger started
FATAL:  role "pio" does not exist
[error] (run-main-0) org.postgresql.util.PSQLException: FATAL: role "pio" does not exist
org.postgresql.util.PSQLException: FATAL: role "pio" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:712)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:67)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:406)
	at org.postgresql.Driver.connect(Driver.java:274)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.apache.commons.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:77)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	at scalikejdbc.Commons2ConnectionPool.borrow(Commons2ConnectionPool.scala:41)
	at scalikejdbc.DB$.autoCommit(DB.scala:214)
	at io.prediction.data.storage.jdbc.JDBCAccessKeys.<init>(JDBCAccessKeys.scala:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.prediction.data.storage.Storage$.getDataObject(Storage.scala:303)
	at io.prediction.data.storage.Storage$.getDataObjectFromRepo(Storage.scala:263)
	at io.prediction.data.storage.Storage$.getMetaDataAccessKeys(Storage.scala:373)
	at io.prediction.data.api.EventServer$.createEventServer(EventServer.scala:615)
	at EventServerApp$delayedInit$body.apply(EventServerApp.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at EventServerApp$.main(EventServerApp.scala:3)
	at EventServerApp.main(EventServerApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:run for the full output.

**Comment by Talamantez** [comment]
FATAL:  role "pio" does not exist
[error] (run-main-0) org.postgresql.util.PSQLException: FATAL: role "pio" does not exist
org.postgresql.util.PSQLException: FATAL: role "pio" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:712)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:67)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:406)
	at org.postgresql.Driver.connect(Driver.java:274)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.apache.commons.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:77)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
	at scalikejdbc.Commons2ConnectionPool.borrow(Commons2ConnectionPool.scala:41)
	at scalikejdbc.DB$.autoCommit(DB.scala:214)
	at io.prediction.data.storage.jdbc.JDBCAccessKeys.<init>(JDBCAccessKeys.scala:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.prediction.data.storage.Storage$.getDataObject(Storage.scala:303)
	at io.prediction.data.storage.Storage$.getDataObjectFromRepo(Storage.scala:263)
	at io.prediction.data.storage.Storage$.getMetaDataAccessKeys(Storage.scala:373)
	at io.prediction.data.api.EventServer$.createEventServer(EventServer.scala:615)
	at EventServerApp$delayedInit$body.apply(EventServerApp.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at EventServerApp$.main(EventServerApp.scala:3)
	at EventServerApp.main(EventServerApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by iamShantanu101** [comment]
You need to create a user in postgresql with name "pio".

**Comment by Talamantez** [comment]
then: 

'createuser pio
createuser: creation of new role failed: ERROR:  role "pio" already exists'

**Comment by Abhilash-Chandran** [comment]
**For Ubuntu 16.04:**
This helped me.
[PostgreSQL for Ubuntu](https://help.ubuntu.com/community/PostgreSQL
)
Check the section "Aternative server setup".
