### ISSUE TITLE
Pio train v0.11.0-incubating

### ISSUE THREAD

**Issue by dannyshox** [apache/incubator-predictionio#380]
Hi,

I'm getting this error when trying to train locally (it builds fine & it also builds, trains and deploys OK on Heroku using  https://github.com/heroku/predictionio-buildpack.git).

**Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;**
	`at scopt.OptionParser.parse(options.scala:370)
	at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:137)
	at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at `org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by dszeto** [comment]
Hi, please redirect usage questions to user@predictionio.incubator.apache.org, and development question to dev@predictionio.incubator.apache.org for more exposure to the rest of the community. Subscription instructions can be found at http://predictionio.incubator.apache.org/support/.

Can you provide more information such as the template you have tried, your environment locally, how you built PredictionIO, etc?
